//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurora.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurora.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SELECT b.name AS &quot;tableName&quot;, a.name AS &quot;columnName&quot;, c.name AS &quot;type&quot;, a.column_id AS &quot;order&quot;, a.max_length AS &quot;length&quot;, a.precision, a.scale, CASE WHEN a.is_nullable = 0 THEN &apos;×&apos; ELSE &apos;〇&apos; END AS &quot;boolnull&quot;, CASE WHEN a.is_identity = 0 THEN &apos;0&apos; ELSE &apos;1&apos; END AS &quot;オートナンバー&quot;, CASE WHEN a.default_object_id = 0 THEN &apos;×&apos; ELSE d.definition END AS &apos;デフォルト値&apos;, CASE WHEN f.index_column_id IS NOT NULL AND e.is_primary_key = 1 THEN &apos;PK&apos; ELSE &apos;×&apos; END AS &apos;PK&apos; FROM sys.columns AS a LEFT OUTER JOIN sys.objects AS b ON  a.obje [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSSQL_COLUMNS {
            get {
                return ResourceManager.GetString("MSSQL_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT name FROM sys.databases ORDER BY database_id; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSSQL_DATABASES {
            get {
                return ResourceManager.GetString("MSSQL_DATABASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT o.name AS name, i.Rows AS rows, COUNT(s.column_id) AS columns FROM sysindexes i, sysobjects o INNER JOIN sys.columns s ON  s.object_id = o.id WHERE o.xtype = &apos;U&apos; AND o.id = i.id AND i.indid &lt; 2 AND o.name &lt;&gt; &apos;dtproperties&apos; GROUP BY o.name, i.Rows ORDER BY o.name; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSSQL_TABLES {
            get {
                return ResourceManager.GetString("MSSQL_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT table_name AS &apos;tableName&apos;, column_name AS &apos;columnName&apos;, data_type AS &apos;type&apos;, character_maximum_length AS &apos;length&apos;, CASE WHEN is_nullable = &apos;NO&apos; THEN &apos;×&apos; ELSE &apos;〇&apos; END AS &apos;boolnull&apos;, column_key AS &apos;pk&apos; FROM information_schema.columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MYSQL_COLUMNS {
            get {
                return ResourceManager.GetString("MYSQL_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHOW Databases; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MYSQL_DATABASES {
            get {
                return ResourceManager.GetString("MYSQL_DATABASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT T.table_name AS &apos;name&apos;, cast(T.table_rows AS signed int) AS &apos;rows&apos;, cast(COUNT(*) AS signed int) AS &apos;columns&apos; FROM information_schema.Tables T LEFT OUTER JOIN information_schema.columns C ON  T.table_catalog = C.table_catalog AND T.table_schema = C.table_schema AND T.table_name = C.table_name WHERE T.table_schema = &apos;{0}&apos; GROUP BY T.table_catalog, T.table_schema, T.table_name, T.table_rows; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MYSQL_TABLES {
            get {
                return ResourceManager.GetString("MYSQL_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT * FROM USER_TAB_COLUMNS; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ORACLE_COLUMNS {
            get {
                return ResourceManager.GetString("ORACLE_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT table_name AS name FROM user_tables; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ORACLE_TABLES {
            get {
                return ResourceManager.GetString("ORACLE_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT c.table_name AS tableName, c.column_name AS columnName, c.data_type AS TYPE, c.character_maximum_length AS LENGTH, CASE WHEN is_nullable = &apos;NO&apos; THEN &apos;×&apos; ELSE &apos;〇&apos; END AS boolnull, CASE WHEN tc.constraint_type = &apos;PRIMARY KEY&apos; THEN &apos;〇&apos; ELSE &apos;×&apos; END AS pk FROM information_schema.columns c LEFT OUTER JOIN information_schema.constraint_column_usage ccu ON  c.table_name = ccu.table_name AND c.column_name = ccu.column_name LEFT OUTER JOIN information_schema.table_constraints tc ON  tc.table_catalog = c.table [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PGSQL_COLUMNS {
            get {
                return ResourceManager.GetString("PGSQL_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT datname AS name FROM pg_database; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PGSQL_DATABASES {
            get {
                return ResourceManager.GetString("PGSQL_DATABASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT relname AS name FROM pg_stat_user_tables; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PGSQL_TABLES {
            get {
                return ResourceManager.GetString("PGSQL_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRAGMA TABLE_INFO({0}); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQLITE_COLUMNS {
            get {
                return ResourceManager.GetString("SQLITE_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT name FROM sqlite_master WHERE TYPE = &apos;table&apos;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQLITE_TABLES {
            get {
                return ResourceManager.GetString("SQLITE_TABLES", resourceCulture);
            }
        }
    }
}
